# group: edge

# sudo: required

dist: xenial

language: java

jdk:
  - oraclejdk9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - gcc
      - g++
      - gcc-multilib
      - g++-multilib
      - libtool
      - python3
      - python3-dev
      - python3-pip
      - wget
      - pkg-config
      - zip
      - zlib1g-dev
      - google-perftools
      - libgoogle-perftools-dev

env:
  # - BAZEL_VERSION=2.0.0 CC=gcc-4.8 CXX=g++-4.8 CPP=cpp-4.8 CXXCPP=cpp-4.8 ENABLE_HEAPCHECK=1
  - BAZEL_VERSION=2.0.0 ENABLE_HEAPCHECK=1

before_install:
  # download and install bazel
  - wget -q "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
  - chmod +x bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh
  - ./bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh --user

before_script:
  # install python module for wheel files
  # required for python packaging
  # - sudo pip install wheel
  - ./bazel_configure.py

script:
  - which gcc
  - gcc --version
  - which g++
  - g++ --version
  - which python3
  - python3 --version
  - which pip3
  - pip3 --version
  - scripts/travis/ci.sh
